[project]
name = "local-federated-catalog"
version = "0.1.0"
description = "Funcionalities for fetching catalogs."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.7",
    "hishel[async]>=1.0.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "pydantic_settings>=2.13.1",
    "pyld>=3.0.0",
    "uvicorn>=0.51.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "python-dotenv>=1.2.2",
    "respx>=0.22.0",
    "ruff>=0.15.0",
    "ty>=0.0.59",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["local_fc*"]

[tool.uv]
exclude-newer = "2 days"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=local_fc --cov-report=term-missing"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
src = ["src/local_fc", "tests"]
target-version = "py314"
exclude = ["alembic"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["local_fc", "tests"]

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []
select = ["ALL"]
ignore = [
  "B008",    # depends in argument defaults
  "D100",    # module docstring
  "D104",    # package docstring
  "D203",    # blank line before class
  "D212",    # multi line summary first line
  "E501",    # line length
  "S101",    # use of assert
  "TC001",   # move into type-checking block
  "TC002",   # move into type-checking block
  "TC003",   # move into type-checking block
  "ANN401",  # dynamically typed expressions
  "BLE001",  # blind except catching
  "COM812",  # add trailing comma
  "CPY",     # copyright
  "FAST003", # unused path parameter
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "ARG",     # unused argument
    "TRY",     # tryceratops
    "S106",    # hardcoded password assignment
    "PT012",   # single statement in pytest raises
    "PLR2004", # magic value in comparison
    "SLF001",  # private member accessed
]

[tool.ty.rules]
all = "error"
